# These are supported funding model platforms

# GitHub Sponsors
github: [jaityagi11]

# Open Collective
# open_collective: safechange-core

# Patreon
# patreon: safechange

# Ko-fi
# ko_fi: safechange

# Custom donation URLs
# custom: ['https://github.com/jaityagi11/safechange-core']
